// (c) Space Exodus Team - EXDS-RL with CLA
namespace Content.Server._Exodus.Economy;

/// <summary>
/// A document generated by a transaction, whose issuance must not create another sellable commodity.
/// Applied to the issued entity, not its prototype: ordinary purchased stationery retains its value.
/// </summary>
[RegisterComponent]
public sealed partial class MarketReceiptComponent : Component;
