// (c) Space Exodus Team - EXDS-RL with CLA
namespace Content.Server._Exodus.Economy;

/// <summary>Orders stock types before the descendants their delivery would recreate.</summary>
public static class MarketShipyardStockPlan
{
    /// <summary>
    /// Each composition contains quantities regenerated by one parent, excluding the parent itself.
    /// Leaves must have an empty composition. Descendants outside the candidate set do not affect order.
    /// Returns an empty result on a cycle or invalid quantity; no stock budgets are changed here.
    /// </summary>
    public static bool TryOrder(
        IReadOnlyDictionary<string, IReadOnlyDictionary<string, double>> compositions,
        out List<string> order)
    {
        order = new List<string>(compositions.Count);
        var incoming = new Dictionary<string, int>(compositions.Count, StringComparer.Ordinal);
        foreach (var key in compositions.Keys)
            incoming.Add(key, 0);

        foreach (var contents in compositions.Values)
        {
            foreach (var (child, quantity) in contents)
            {
                if (!double.IsFinite(quantity) || quantity < 0)
                    return false;

                if (quantity > 0 && incoming.TryGetValue(child, out var count))
                    incoming[child] = count + 1;
            }
        }

        var ready = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var (key, count) in incoming)
        {
            if (count == 0)
                ready.Add(key);
        }

        while (ready.Count > 0)
        {
            var key = ready.Min!;
            ready.Remove(key);
            order.Add(key);

            foreach (var (child, quantity) in compositions[key])
            {
                if (quantity <= 0 || !incoming.TryGetValue(child, out var count))
                    continue;

                incoming[child] = count - 1;
                if (count == 1)
                    ready.Add(child);
            }
        }

        if (order.Count == compositions.Count)
            return true;

        order.Clear();
        return false;
    }
}
