using System.Numerics;
using Content.Shared._Exodus.Gimmicks.SlotMachine;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Exodus.Gimmicks.SlotMachine.Ui;

[GenerateTypedNameReferences]
public sealed partial class SlotMachineWindow : DefaultWindow
{
    [Dependency] private readonly IRobustRandom _random = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    public event Action<int>? OnSpin;
    public event Action<int>? OnInsert;
    public event Action? OnCollect;

    private static readonly TimeSpan AnimationInterval = TimeSpan.FromMilliseconds(120);
    private static readonly Vector2 ReelTextureSize = new(24, 24);
    private static readonly Color QuestionMarkColor = Color.FromHex("#555555");

    private const int PayoutSymbolsSeparation = 2;
    private const int InsertAmountSmall = 10;
    private const int InsertAmountMedium = 100;
    private const int InsertAmountLarge = 1000;
    private const int InsertAmountHuge = 5000;
    private const int BetAdjustSmall = 100;
    private const int BetAdjustLarge = 1000;
    private const int BetAdjustHuge = 5000;

    private int _bet = SlotMachineComponent.MinBet;
    private bool _isSpinning;
    private TimeSpan _lastAnimationFrame;
    private bool _payoutTableInitialized;
    private List<SlotMachineReelDef> _reelPools = new();

    public SlotMachineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SpinButton.OnPressed += _ => OnSpin?.Invoke(_bet);
        CollectButton.OnPressed += _ => OnCollect?.Invoke();
        Insert10Button.OnPressed += _ => OnInsert?.Invoke(InsertAmountSmall);
        Insert100Button.OnPressed += _ => OnInsert?.Invoke(InsertAmountMedium);
        Insert1000Button.OnPressed += _ => OnInsert?.Invoke(InsertAmountLarge);
        Insert5000Button.OnPressed += _ => OnInsert?.Invoke(InsertAmountHuge);
        BetMinus1000Button.OnPressed += _ => SetBet(_bet - BetAdjustLarge);
        BetMinus100Button.OnPressed += _ => SetBet(_bet - BetAdjustSmall);
        BetPlus100Button.OnPressed += _ => SetBet(_bet + BetAdjustSmall);
        BetPlus1000Button.OnPressed += _ => SetBet(_bet + BetAdjustLarge);
        BetPlus5000Button.OnPressed += _ => SetBet(_bet + BetAdjustHuge);

        Insert10Button.Text = Loc.GetString("slot-machine-ui-insert", ("amount", InsertAmountSmall));
        Insert100Button.Text = Loc.GetString("slot-machine-ui-insert", ("amount", InsertAmountMedium));
        Insert1000Button.Text = Loc.GetString("slot-machine-ui-insert", ("amount", InsertAmountLarge));
        Insert5000Button.Text = Loc.GetString("slot-machine-ui-insert", ("amount", InsertAmountHuge));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_isSpinning || _timing.RealTime - _lastAnimationFrame < AnimationInterval)
            return;

        _lastAnimationFrame = _timing.RealTime;
        SetReelTexture(Reel0Rect, GetRandomSymbol(0));
        SetReelTexture(Reel1Rect, GetRandomSymbol(1));
        SetReelTexture(Reel2Rect, GetRandomSymbol(2));
    }

    public void UpdateState(SlotMachineBoundUserInterfaceState state)
    {
        _isSpinning = state.IsSpinning;
        _reelPools = state.ReelPools;
        InitializePayoutTable(state.Rules);

        if (!state.IsSpinning)
        {
            if (state.Reels.Count > 0)
                SetReelTexture(Reel0Rect, state.Reels[0]);
            if (state.Reels.Count > 1)
                SetReelTexture(Reel1Rect, state.Reels[1]);
            if (state.Reels.Count > 2)
                SetReelTexture(Reel2Rect, state.Reels[2]);
        }

        CreditsLabel.Text = Loc.GetString("slot-machine-ui-deposit", ("amount", state.StoredCredits));
        var winSymbol = state.Reels.Count > 0 ? GetSymbolName(state.Reels[0]) : string.Empty;
        PayoutLabel.Text = state.IsSpinning
            ? Loc.GetString("slot-machine-ui-spinning")
            : state.IsWin
                ? Loc.GetString(state.WinText, ("amount", state.LastPayout), ("symbol", winSymbol))
                : state.LastBet > 0
                    ? Loc.GetString("slot-machine-ui-lose")
                    : Loc.GetString("slot-machine-ui-luck");

        _bet = Math.Max(SlotMachineComponent.MinBet,
            Math.Min(_bet, state.StoredCredits > 0 ? state.StoredCredits : SlotMachineComponent.MinBet));
        BetLabel.Text = _bet.ToString();

        SpinButton.Disabled = state.IsSpinning || state.StoredCredits < SlotMachineComponent.MinBet;
        CollectButton.Disabled = state.IsSpinning || state.StoredCredits < 1;
        BetMinus1000Button.Disabled = state.IsSpinning;
        BetMinus100Button.Disabled = state.IsSpinning;
        BetPlus100Button.Disabled = state.IsSpinning;
        BetPlus1000Button.Disabled = state.IsSpinning;
        BetPlus5000Button.Disabled = state.IsSpinning;
        Insert10Button.Disabled = state.IsSpinning;
        Insert100Button.Disabled = state.IsSpinning;
        Insert1000Button.Disabled = state.IsSpinning;
        Insert5000Button.Disabled = state.IsSpinning;
    }

    private void InitializePayoutTable(List<SlotMachineRule> rules)
    {
        if (_payoutTableInitialized)
            return;

        _payoutTableInitialized = true;
        PayoutTableContainer.DisposeAllChildren();

        foreach (var rule in rules)
        {
            if (rule.Symbols.Count == 0)
                continue;

            var symbolsContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = PayoutSymbolsSeparation,
            };

            var reelCount = _reelPools.Count;
            var startIndex = Math.Clamp(rule.Index ?? 0, 0, reelCount);
            var endIndex = Math.Min(startIndex + rule.Symbols.Count, reelCount);
            for (var i = 0; i < reelCount; i++)
            {
                if (i >= startIndex && i < endIndex)
                {
                    var texture = new TextureRect
                    {
                        MinSize = ReelTextureSize,
                        HorizontalAlignment = HAlignment.Center,
                        VerticalAlignment = VAlignment.Center,
                        Stretch = TextureRect.StretchMode.KeepAspectCentered,
                    };
                    SetReelTexture(texture, rule.Symbols[i - startIndex]);
                    symbolsContainer.AddChild(texture);
                    continue;
                }

                symbolsContainer.AddChild(new Label
                {
                    Text = "?",
                    MinSize = ReelTextureSize,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    FontColorOverride = QuestionMarkColor,
                    Align = Label.AlignMode.Center,
                });
            }

            PayoutTableContainer.AddChild(symbolsContainer);
            PayoutTableContainer.AddChild(new Label
            {
                Text = $"x{rule.Multiplier}",
                VerticalAlignment = VAlignment.Center,
                FontColorOverride = rule.MultiplierColor,
            });
        }
    }

    private void SetBet(int value)
    {
        _bet = Math.Max(SlotMachineComponent.MinBet, value);
        BetLabel.Text = _bet.ToString();
    }

    private void SetReelTexture(TextureRect rect, string symbolId)
    {
        rect.Texture = null;
        foreach (var pool in _reelPools)
        {
            foreach (var symbol in pool.Symbols)
            {
                if (symbol.Id != symbolId || symbol.Icon is not SpriteSpecifier.Rsi rsi)
                    continue;

                var resource = _resourceCache.GetResource<RSIResource>(rsi.RsiPath);
                if (resource.RSI.TryGetState(rsi.RsiState, out var state))
                    rect.Texture = state.Frame0;

                return;
            }
        }
    }

    private string GetSymbolName(string symbolId)
    {
        foreach (var pool in _reelPools)
        {
            foreach (var symbol in pool.Symbols)
            {
                if (symbol.Id == symbolId)
                    return Loc.GetString(symbol.Name);
            }
        }

        return string.Empty;
    }

    private string GetRandomSymbol(int reelIndex)
    {
        if (_reelPools.Count <= reelIndex)
            return string.Empty;

        var totalWeight = 0f;
        SlotMachineSymbolDef? lastSymbol = null;
        foreach (var symbol in _reelPools[reelIndex].Symbols)
        {
            if (!float.IsFinite(symbol.Weight) || symbol.Weight <= 0f)
                continue;

            totalWeight += symbol.Weight;
            lastSymbol = symbol;
        }

        if (lastSymbol == null || totalWeight <= 0f || !float.IsFinite(totalWeight))
            return string.Empty;

        var roll = _random.NextFloat(totalWeight);
        foreach (var symbol in _reelPools[reelIndex].Symbols)
        {
            if (!float.IsFinite(symbol.Weight) || symbol.Weight <= 0f)
                continue;

            roll -= symbol.Weight;
            if (roll <= 0f)
                return symbol.Id;
        }

        return lastSymbol.Id;
    }
}
