using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Conveyor;

[GenerateTypedNameReferences]
public sealed partial class ConveyorWindow : DefaultWindow
{
    public event Action<byte>? OnTierSelected;

    public ConveyorWindow()
    {
        RobustXamlLoader.Load(this);

        Tier1.OnPressed += _ => OnTierSelected?.Invoke(1);
        Tier2.OnPressed += _ => OnTierSelected?.Invoke(2);
        Tier3.OnPressed += _ => OnTierSelected?.Invoke(3);
    }
}
