using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.VendingMachines;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Content.Shared._NF.Bank; // Frontier
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using Robust.Client.UserInterface;
using Content.Shared.IdentityManagement;
using Robust.Client.Graphics;

namespace Content.Client.VendingMachines.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VendingMachineMenu : FancyWindow
    {
        [Dependency] private IPrototypeManager _prototypeManager = default!;
        [Dependency] private IEntityManager _entityManager = default!;
        private readonly Dictionary<EntProtoId, EntityUid> _dummies = [];

        public event Action<GUIBoundKeyEventArgs, ListData>? OnItemSelected;

        private readonly StyleBoxFlat _styleBox = new() { BackgroundColor = new Color(70, 73, 102) };

        public VendingMachineMenu()
        {
            MinSize = SetSize = new Vector2(250, 150);
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            VendingContents.SearchBar = SearchBar;
            VendingContents.DataFilterCondition += DataFilterCondition;
            VendingContents.GenerateItem += GenerateButton;
            VendingContents.ItemKeyBindDown += (args, data) => OnItemSelected?.Invoke(args, data);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            // Don't clean up dummies during disposal or we'll just have to spawn them again
            if (!disposing)
                return;

            // Delete any dummy items we spawned
            foreach (var entity in _dummies.Values)
            {
                _entityManager.QueueDeleteEntity(entity);
            }
            _dummies.Clear();
        }

        private bool DataFilterCondition(string filter, ListData data)
        {
            if (data is not VendorItemsListData { ItemText: var text })
                return false;

            if (string.IsNullOrEmpty(filter))
                return true;

            return text.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
        }

        private void GenerateButton(ListData data, ListContainerButton button)
        {
            if (data is not VendorItemsListData { ItemProtoID: var protoID, ItemText: var text, CanPurchase: var canPurchase })
                return;

            button.AddChild(new VendingMachineItem(protoID, text));

            button.Disabled = !canPurchase; // Exodus: unknown prices cannot be purchased.
            button.ToolTip = text;
            button.StyleBoxOverride = _styleBox;
        }

        /// <summary>
        /// Populates the list of available items on the vending machine interface
        /// and sets icons based on their prototypes
        /// </summary>
        public void Populate(List<VendingMachineInventoryEntry> inventory, IReadOnlyDictionary<EntProtoId, int?> prices, int balance, int? cashSlotBalance) // Exodus: authoritative server prices
        {
            UpdateBalance(balance); // Frontier
            UpdateCashSlotBalance(cashSlotBalance); // Frontier

            if (inventory.Count == 0 && VendingContents.Visible)
            {
                SearchBar.Visible = false;
                VendingContents.Visible = false;

                var outOfStockLabel = new Label()
                {
                    Text = Loc.GetString("vending-machine-component-try-eject-out-of-stock"),
                    Margin = new Thickness(4, 4),
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Stretch,
                    HorizontalAlignment = HAlignment.Center
                };

                MainContainer.AddChild(outOfStockLabel);

                SetSizeAfterUpdate(outOfStockLabel.Text.Length, 0);

                return;
            }

            var longestEntry = string.Empty;
            var listData = new List<VendorItemsListData>();

            for (var i = 0; i < inventory.Count; i++)
            {
                var entry = inventory[i];

                if (!_prototypeManager.TryIndex(entry.ID, out var prototype))
                    continue;

                if (!_dummies.TryGetValue(entry.ID, out var dummy))
                {
                    dummy = _entityManager.Spawn(entry.ID);
                    _dummies.Add(entry.ID, dummy);
                }

                var itemName = Identity.Name(dummy, _entityManager);
                // Exodus-begin: the server includes the purchase floor and current market pressure.
                var available = prices.TryGetValue(entry.ID, out var price) && price.HasValue;
                var priceText = available
                    ? BankSystemExtensions.ToSpesoString(price!.Value)
                    : Loc.GetString("market-purchase-unavailable");
                var itemText = entry.Amount != uint.MaxValue
                    ? Loc.GetString("vending-machine-market-item", ("price", priceText), ("name", itemName), ("amount", entry.Amount))
                    : Loc.GetString("vending-machine-market-item-unlimited", ("price", priceText), ("name", itemName));
                // Exodus-end

                if (itemText.Length > longestEntry.Length)
                    longestEntry = itemText;

                listData.Add(new VendorItemsListData(prototype!.ID, itemText, i, available && entry.Amount > 0)); // Exodus
            }

            VendingContents.PopulateList(listData);

            SetSizeAfterUpdate(longestEntry.Length, inventory.Count);
        }

        // Exodus: price estimation moved to the server purchase quote.

        // Frontier
        public void UpdateBalance(int balance)
        {
            BalanceLabel.Text = BankSystemExtensions.ToSpesoString(balance);
        }

        public void UpdateCashSlotBalance(int? balance)
        {
            CashSlotControls.Visible = balance != null;
            if (balance != null)
                CashSlotLabel.Text = BankSystemExtensions.ToSpesoString(balance.Value);
        }
        // End Frontier

        private void SetSizeAfterUpdate(int longestEntryLength, int contentCount)
        {
            SetSize = new Vector2(Math.Clamp((longestEntryLength + 2) * 12, 250, 400),
                Math.Clamp(contentCount * 50, 150, 350));
        }
    }
}

public record VendorItemsListData(EntProtoId ItemProtoID, string ItemText, int ItemIndex, bool CanPurchase = true) : ListData; // Exodus
