// (c) Space Exodus Team - EXDS-RL with CLA
using System.Linq;
using Content.Server._Exodus.Economy;
using Content.Server.Chemistry.Components;
using Content.Server.Construction;
using Content.Server.Construction.Components;
using Content.Server.Station.Systems;
using Content.Shared.Chemistry;
using Content.Shared.Construction.Components;
using Content.Shared.Containers.ItemSlots;
using Robust.Shared.Containers;
using Robust.Shared.GameObjects;
using Robust.Shared.Map;

namespace Content.IntegrationTests.Tests._Exodus.Economy;

[TestFixture]
public sealed class MarketReagentDispenserTest
{
    [TestPrototypes]
    private const string Prototypes = """
        - type: entity
          id: ExodusMarketDispenserJug
          parent: JugAluminium
          components:
          - type: StaticPrice
            price: 10000

        - type: reagentDispenserInventory
          id: ExodusMarketDispenserInventory
          inventory:
          - ExodusMarketDispenserJug
          - ExodusMarketDispenserJug
          - ExodusMarketDispenserJug

        - type: entity
          id: ExodusMarketDispenser
          parent: ChemDispenser
          components:
          - type: ReagentDispenser
            pack: ExodusMarketDispenserInventory
            baseNumStorageSlots: 1
            extraSlotsPerTier: 1

        - type: entity
          id: ExodusMarketDispenserUpgraded
          parent: ExodusMarketDispenser
          components:
          - type: Machine
            partOverrides:
              MatterBin: AdvancedMatterBinStockPart

        - type: entity
          id: ExodusMarketDispenserBeaker
          parent: ExodusMarketDispenser
          components:
          - type: ReagentDispenser
            beakerSlot:
              startingItem: Beaker

        - type: entity
          id: ExodusMarketDispenserStation
          parent: BaseStationCargoMarket
          components:
          - type: StationTracker
          - type: CargoMarketData
            whitelistOverride:
              tags:
              - ChemDispensable
        """;

    [TestCase("ChemDispenser", 20)]
    [TestCase("ChemDispenserEmpty", 0)]
    [TestCase("ExodusMarketDispenser", 1)]
    [TestCase("ExodusMarketDispenserUpgraded", 3)]
    [TestCase("ExodusMarketDispenserBeaker", 1)]
    public async Task PrototypeBasketIncludesOnlyTheDispensersGeneratedContents(string prototype, int filledSlots)
    {
        await using var pair = await PoolManager.GetServerClient();
        var map = await pair.CreateTestMap();
        var entities = pair.Server.EntMan;
        await pair.Server.WaitAssertion(() =>
        {
            var dispenser = entities.SpawnEntity(prototype, map.GridCoords);
            try
            {
                var component = entities.GetComponent<ReagentDispenserComponent>(dispenser);
                Assert.That(component.StorageSlots.Count(slot => slot.Item != null), Is.EqualTo(filledSlots));
                var baskets = entities.System<MarketBasketSystem>();
                Assert.That(baskets.TryGetPrototypeBasket(prototype, out var estimated, out var failure), Is.True, failure);
                Assert.That(baskets.TryGetEntityBasket(dispenser, out var live, out failure), Is.True, failure);
                Assert.Multiple(() =>
                {
                    Assert.That(estimated.Exact, Is.True);
                    Assert.That(estimated.NominalValue, Is.EqualTo(live.NominalValue).Within(0.001),
                        "The purchase must price the cartridges actually generated by MapInit.");
                    foreach (var commodity in live.Lines.GroupBy(line => line.MarketKey))
                    {
                        Assert.That(estimated.Lines.Where(line => line.MarketKey == commodity.Key).Sum(line => line.Quantity),
                            Is.EqualTo(commodity.Sum(line => line.Quantity)).Within(0.001), commodity.Key);
                    }
                });
                if (prototype == "ExodusMarketDispenserBeaker")
                    Assert.That(entities.System<ItemSlotsSystem>().GetItemOrNull(dispenser, SharedReagentDispenser.OutputSlotName),
                        Is.Not.Null, "The generated output beaker is part of the purchased machine.");
            }
            finally
            {
                entities.DeleteEntity(dispenser);
            }
        });
        await pair.CleanReturnAsync();
    }

    [Test]
    public async Task PurchaseCoversResaleOfGeneratedDispenserCartridges()
    {
        await using var pair = await PoolManager.GetServerClient();
        var map = await pair.CreateTestMap();
        var entities = pair.Server.EntMan;
        await pair.Server.WaitAssertion(() =>
        {
            var dispenser = entities.SpawnEntity("ExodusMarketDispenserUpgraded", map.GridCoords);
            var market = entities.System<DynamicMarketSystem>();
            Assert.That(entities.System<MarketBasketSystem>().TryGetEntityBasket(dispenser, out var basket, out var failure),
                Is.True, failure);
            try
            {
                foreach (var line in basket.Lines)
                    market.SetFactor(line.MarketKey, 1);
                Assert.That(entities.System<MarketPurchaseSystem>().TryQuotePrototypeBuy(
                    "ExodusMarketDispenserUpgraded", 1, 1000, 1, out var quote, ceiling: new MarketSellCeiling(1.5, 1.5)), Is.True);
                market.CommitTransaction(quote!.Transaction);
                var transaction = new MarketTransactionState();
                double resale = 0;
                foreach (var line in basket.Lines)
                {
                    resale += market.CalculateSequentialSellValue(line.MarketKey, line.UnitBasePrice, line.Quantity,
                        1, 1.5, transaction, false);
                }
                Assert.That(quote.TotalPrice, Is.GreaterThan(DynamicMarketSystem.RoundSellPayout(resale)),
                    "Cheap machine catalog pricing must not omit freshly generated high-value cartridges.");
            }
            finally
            {
                foreach (var line in basket.Lines)
                    market.ResetKey(line.MarketKey);
                entities.DeleteEntity(dispenser);
            }
        });
        await pair.CleanReturnAsync();
    }

    [TestCase(false)]
    [TestCase(true)]
    public async Task DispenserStockSuppressesOnlyCartridgesRecreatedByItsPrototype(bool upgrade)
    {
        await using var pair = await PoolManager.GetServerClient();
        var map = await pair.CreateTestMap();
        var entities = pair.Server.EntMan;
        await pair.Server.WaitAssertion(() =>
        {
            var inventory = entities.System<MarketInventorySystem>();
            inventory.Clear();
            var station = entities.SpawnEntity("ExodusMarketDispenserStation", MapCoordinates.Nullspace);
            entities.System<StationSystem>().SetStation(station, station);
            var dispenser = entities.SpawnEntity("ExodusMarketDispenser", map.GridCoords);
            try
            {
                if (upgrade)
                {
                    var machine = entities.GetComponent<MachineComponent>(dispenser);
                    var oldPart = machine.PartContainer.ContainedEntities.First(uid =>
                        entities.HasComponent<MachinePartComponent>(uid));
                    entities.DeleteEntity(oldPart);
                    var containers = entities.System<SharedContainerSystem>();
                    var part = entities.SpawnEntity("AdvancedMatterBinStockPart", map.GridCoords);
                    Assert.That(containers.Insert(part, machine.PartContainer), Is.True);
                    entities.System<ConstructionSystem>().RefreshParts(dispenser, machine);
                    var extra = entities.SpawnEntity("ExodusMarketDispenserJug", map.GridCoords);
                    var slot = containers.GetContainer(dispenser, ReagentDispenserComponent.BaseStorageSlotId + 1);
                    Assert.That(containers.Insert(extra, slot), Is.True);
                }

                var sale = new MarketGoodsSoldEvent([dispenser], station);
                entities.EventBus.RaiseEvent(EventSource.Local, ref sale);
                Assert.That(inventory.TryGetStock("ExodusMarketDispenser", out var machineStock), Is.True);
                Assert.That(machineStock!.Quantity, Is.EqualTo(1));
                Assert.That(inventory.TryGetStock("ExodusMarketDispenserJug", out var jugStock), Is.EqualTo(upgrade),
                    "Only the prototype's regenerated slots may suppress separately stocked contents.");
                if (upgrade)
                    Assert.That(jugStock!.Quantity, Is.EqualTo(1));
            }
            finally
            {
                entities.DeleteEntity(dispenser);
                entities.DeleteEntity(station);
                inventory.Clear();
            }
        });
        await pair.CleanReturnAsync();
    }
}
