using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.Mining.AutoMining;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Mining.AutoMining;

[GenerateTypedNameReferences]
public sealed partial class BulkAutoMiningWindow : FancyWindow
{
    private readonly Dictionary<NetEntity, BulkAutoMiningLaserControl> _laserCards = new();
    private readonly Dictionary<NetEntity, (BoxContainer Row, Label Name, Button Remove)> _targetRows = new();
    private readonly HashSet<NetEntity> _stale = new();

    public event Action? OnStartPressed;
    public event Action? OnStopPressed;
    public event Action<NetEntity>? OnTargetRemoved;
    public BulkAutoMiningNavControl RadarControl => Radar;

    public BulkAutoMiningWindow()
    {
        RobustXamlLoader.Load(this);
        // Reserve both sidebars before measuring the radar and its wrapping hint.
        foreach (var panel in Workspace.Children)
        {
            LayoutContainer.SetAnchorBottom(panel, 1);
            LayoutContainer.SetGrowHorizontal(panel, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(panel, LayoutContainer.GrowDirection.Constrain);
        }

        LayoutContainer.SetMarginRight(TargetsPanel, TargetsPanel.SetWidth);
        LayoutContainer.SetAnchorLeft(LasersPanel, 1);
        LayoutContainer.SetAnchorRight(LasersPanel, 1);
        LayoutContainer.SetMarginLeft(LasersPanel, -LasersPanel.SetWidth);
        LayoutContainer.SetAnchorRight(RadarPanel, 1);
        LayoutContainer.SetMarginLeft(RadarPanel, TargetsPanel.SetWidth + 12);
        LayoutContainer.SetMarginRight(RadarPanel, -LasersPanel.SetWidth - 12);

        StartButton.OnPressed += _ => OnStartPressed?.Invoke();
        StopButton.OnPressed += _ => OnStopPressed?.Invoke();
    }

    public void SetConsole(EntityUid consoleEntity)
    {
        Radar.SetConsole(consoleEntity);
    }

    protected override void Opened()
    {
        base.Opened();
        if (Parent == null)
            return;

        var available = Vector2.Max(MinSize, Parent.Size - new Vector2(20));
        SetSize = Vector2.Min(SetSize, available);
        Measure(available);
    }

    public void UpdateState(BulkAutoMiningBoundUserInterfaceState state)
    {
        Radar.UpdateMiningState(state);
        var mining = UpdateLasers(state.LinkedLasers);
        UpdateTargets(state);

        var waiting = state.Active && mining == 0;
        MiningStatus.Text = Loc.GetString(state.Active
            ? waiting ? "bulk-auto-mining-status-waiting" : "bulk-auto-mining-status-active"
            : state.CanStart ? "bulk-auto-mining-status-ready" : "bulk-auto-mining-status-idle");
        MiningStatus.FontColorOverride = state.Active ? Color.FromHex("#F2B85F") : Color.FromHex("#C3D9D7");
        LaserSummary.Text = Loc.GetString("bulk-auto-mining-laser-summary",
            ("mining", mining), ("total", state.LinkedLasers.Count));

        var hint = state.Active
            ? waiting ? "bulk-auto-mining-hint-waiting" : "bulk-auto-mining-hint-active"
            : state.LinkedLasers.Count == 0 ? "bulk-auto-mining-no-lasers"
            : !state.CanStart ? "bulk-auto-mining-start-no-ready-emitter"
            : state.SelectedTargets.Count == 0 ? "bulk-auto-mining-select-hint"
            : "bulk-auto-mining-hint-ready";
        OperationHint.SetMessage(Loc.GetString(hint));
        RadarHint.SetMessage(Loc.GetString(state.Active
            ? "bulk-auto-mining-select-while-active" : "bulk-auto-mining-radar-hint"));
        SelectedTargetsSummary.Text = Loc.GetString("bulk-auto-mining-selected-targets-summary",
            ("count", state.SelectedTargets.Count), ("max", state.MaxSelectableTargets));

        StartButton.Disabled = state.Active || !state.CanStart || state.SelectedTargets.Count == 0;
        StartButton.ToolTip = StartButton.Disabled ? Loc.GetString(hint) : null;
        StopButton.Disabled = !state.Active;
        MiningProgress.Value = state.TotalTiles > 0
            ? Math.Clamp((float)state.ProcessedTiles / state.TotalTiles, 0, 1) : 0;
        ProgressLabel.Text = state.TotalTiles > 0
            ? Loc.GetString("bulk-auto-mining-progress", ("processed", state.ProcessedTiles), ("total", state.TotalTiles))
            : Loc.GetString("bulk-auto-mining-progress-empty");
    }

    private void UpdateTargets(BulkAutoMiningBoundUserInterfaceState state)
    {
        _stale.Clear();
        _stale.UnionWith(_targetRows.Keys);
        foreach (var target in state.SelectedTargets)
        {
            _stale.Remove(target.Grid);
            if (!_targetRows.TryGetValue(target.Grid, out var row))
            {
                row = (new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4 },
                    new Label { HorizontalExpand = true, ClipText = true },
                    new Button { Text = Loc.GetString("bulk-auto-mining-remove-target"), MinHeight = 30 });
                var grid = target.Grid;
                row.Remove.OnPressed += _ => OnTargetRemoved?.Invoke(grid);
                row.Row.AddChild(row.Name);
                row.Row.AddChild(row.Remove);
                TargetsBox.AddChild(row.Row);
                _targetRows.Add(grid, row);
            }

            row.Name.Text = target.Name ?? Loc.GetString("bulk-auto-mining-unknown-grid");
            row.Name.ToolTip = row.Name.Text;
            row.Remove.Disabled = state.Active;
            row.Remove.ToolTip = state.Active ? Loc.GetString("bulk-auto-mining-select-while-active") : null;
        }

        foreach (var grid in _stale)
        {
            if (_targetRows.Remove(grid, out var row))
                TargetsBox.RemoveChild(row.Row);
        }

        NoTargetsLabel.Visible = state.SelectedTargets.Count == 0;
    }

    private int UpdateLasers(List<BulkAutoMiningLaserState> lasers)
    {
        _stale.Clear();
        _stale.UnionWith(_laserCards.Keys);
        var mining = 0;
        for (var i = 0; i < lasers.Count; i++)
        {
            var laser = lasers[i];
            _stale.Remove(laser.Emitter);
            if (!_laserCards.TryGetValue(laser.Emitter, out var card))
            {
                card = new BulkAutoMiningLaserControl();
                LasersBox.AddChild(card);
                _laserCards.Add(laser.Emitter, card);
            }

            card.UpdateState(laser, i + 1);
            if (laser.Status == BulkAutoMiningLaserStatus.Mining)
                mining++;
        }

        foreach (var emitter in _stale)
        {
            if (_laserCards.Remove(emitter, out var card))
                LasersBox.RemoveChild(card);
        }

        NoLasersLabel.Visible = lasers.Count == 0;
        return mining;
    }
}
