// (c) Space Exodus Team - EXDS-RL with CLA

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Exodus.Analyzers.Generators.EntityQueryInterceptorGenerator;

[Generator]
public class EntityQueryInterceptorGenerator : IIncrementalGenerator
{
    private readonly struct InvocationCallInfo
    {
        public readonly string MethodName;
        public readonly string ComponentTypeName;
        public readonly int InterceptVersion;
        public readonly string InterceptData;
        public readonly string ReturnType;
        public readonly string ParameterListNoThis;
        public readonly string ArgumentNamesNoThis;

        public InvocationCallInfo(
            string methodName, string componentTypeName,
            int interceptVersion, string interceptData,
            string returnType, string parameterListNoThis, string argumentNamesNoThis)
        {
            MethodName = methodName;
            ComponentTypeName = componentTypeName;
            InterceptVersion = interceptVersion;
            InterceptData = interceptData;
            ReturnType = returnType;
            ParameterListNoThis = parameterListNoThis;
            ArgumentNamesNoThis = argumentNamesNoThis;
        }
    }

    private static bool IsMethodOnEntitySystem(IMethodSymbol method)
    {
        var type = method.ContainingType;
        while (type != null)
        {
            if (type.ToDisplayString() == "Robust.Shared.GameObjects.EntitySystem")
                return true;
            type = type.BaseType;
        }
        return false;
    }

    private static bool IsEntitySystemClass(INamedTypeSymbol symbol)
    {
        var baseType = symbol.BaseType;
        while (baseType != null)
        {
            if (baseType.ToDisplayString() == "Robust.Shared.GameObjects.EntitySystem")
                return true;
            baseType = baseType.BaseType;
        }
        return false;
    }

    private static INamedTypeSymbol? GetContainingClass(SyntaxNode node, SemanticModel model)
    {
        var parent = node.Parent;
        while (parent != null)
        {
            if (parent is TypeDeclarationSyntax typeDecl)
                return model.GetDeclaredSymbol(typeDecl);
            parent = parent.Parent;
        }
        return null;
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("InterceptsLocationAttribute.g.cs", @"
// <auto-generated/>
#pragma warning disable CS0436
namespace System.Runtime.CompilerServices
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    internal sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}
");
        });

        var methodCalls = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is InvocationExpressionSyntax,
            transform: static (ctx, token) => TransformMethodCall(ctx, token)
        ).Where(static info => info is not null)!;

        var combined = methodCalls.Collect();
        context.RegisterSourceOutput(combined, GenerateSource);
    }

    private static (INamedTypeSymbol ContainingClass, InvocationCallInfo Call)? TransformMethodCall(
        GeneratorSyntaxContext ctx, CancellationToken token)
    {
        if (ctx.Node is not InvocationExpressionSyntax invocation)
            return null;

        var model = ctx.SemanticModel;
        if (model.GetSymbolInfo(invocation).Symbol is not IMethodSymbol method)
            return null;

        if (!IsMethodOnEntitySystem(method))
            return null;

        var containingClass = GetContainingClass(invocation, model);
        if (containingClass is null || !IsEntitySystemClass(containingClass))
            return null;

        var methodName = method.Name;
        if (methodName is not ("TryComp" or "HasComp"))
            return null;

        if (method.TypeArguments.Length == 0)
            return null;

        var compType = method.TypeArguments[0];
        if (compType is ITypeParameterSymbol or not INamedTypeSymbol)
            return null;

        if (method.Parameters.Length == 0)
            return null;

        var interceptableLocation = model.GetInterceptableLocation(invocation, token);
        if (interceptableLocation == null)
            return null;
        var version = interceptableLocation.Version;
        var data = interceptableLocation.Data;

        var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var typeFormat = new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
        );

        var paramList = new List<string>();
        var argList = new List<string>();
        foreach (var p in method.Parameters)
        {
            var mod = p.RefKind switch { RefKind.Out => "out ", RefKind.Ref => "ref ", _ => "" };
            var type = p.Type.ToDisplayString(typeFormat);
            var isNullableOut = p.RefKind == RefKind.Out && type.EndsWith("?");
            var paramDecl = isNullableOut
                ? $"[global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] {mod}{type} {p.Name}"
                : $"{mod}{type} {p.Name}";
            paramList.Add(paramDecl);
            argList.Add($"{mod}{p.Name}");
        }

        var callInfo = new InvocationCallInfo(
            methodName,
            ((INamedTypeSymbol)compType).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            version, data,
            returnType,
            string.Join(", ", paramList),
            string.Join(", ", argList)
        );

        return (containingClass, callInfo);
    }

    private static void GenerateSource(SourceProductionContext spc,
        ImmutableArray<(INamedTypeSymbol ContainingClass, InvocationCallInfo Call)?> methodCallsNullable)
    {
        var methodCalls = methodCallsNullable
            .Where(x => x.HasValue)
            .Select(x => x!.Value)
            .ToImmutableArray();

        // Group calls by the assembly that contains the calling EntitySystem.
        var callsByAssembly = new Dictionary<IAssemblySymbol, List<InvocationCallInfo>>(SymbolEqualityComparer.Default);
        foreach (var (containingClass, call) in methodCalls)
        {
            var assembly = containingClass.ContainingAssembly;
            if (!callsByAssembly.TryGetValue(assembly, out var list))
            {
                list = new List<InvocationCallInfo>();
                callsByAssembly[assembly] = list;
            }
            list.Add(call);
        }

        foreach (var kvp in callsByAssembly)
        {
            var assembly = kvp.Key;
            var calls = kvp.Value;
            var uniqueComponents = calls.Select(c => c.ComponentTypeName).Distinct().ToImmutableArray();

            var className = GetCachingSystemClassName(assembly);
            var ns = assembly.Name + ".GameObjects.EntitySystems";

            spc.AddSource($"{className}.g.cs", GenerateCachingSystem(ns, className, uniqueComponents, calls));
        }
    }

    private static string GetCachingSystemClassName(IAssemblySymbol assembly)
    {
        var name = assembly.Name;
        var prefix = string.Empty;
        if (name.StartsWith("Content."))
            prefix = name.Substring("Content.".Length);
        else
            prefix = name.Contains('.') ? name.Substring(name.LastIndexOf('.') + 1) : name;

        if (prefix.Length > 0 && char.IsLower(prefix[0]))
            prefix = char.ToUpperInvariant(prefix[0]) + prefix.Substring(1);

        return prefix + "ComponentCachingSystem";
    }

    private static string GenerateCachingSystem(string ns, string className,
        ImmutableArray<string> componentTypeNames, List<InvocationCallInfo> calls)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using Robust.Shared.GameObjects;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");

        sb.AppendLine($"    public sealed class {className} : EntitySystem");
        sb.AppendLine("    {");

        foreach (var compType in componentTypeNames)
        {
            var fieldName = GetFieldName(compType);
            sb.AppendLine($"        public static global::Robust.Shared.GameObjects.EntityQuery<{compType}> {fieldName};");
        }

        sb.AppendLine();
        sb.AppendLine("        public override void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine("            base.Initialize();");
        foreach (var compType in componentTypeNames)
        {
            var fieldName = GetFieldName(compType);
            sb.AppendLine($"            {fieldName} = GetEntityQuery<{compType}>();");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }"); // end class

        sb.AppendLine();
        sb.AppendLine($"    public static class {className}_Interceptors");
        sb.AppendLine("    {");
        var counter = 0;
        foreach (var call in calls)
        {
            var fieldName = GetFieldName(call.ComponentTypeName);
            var parameters = "this EntitySystem __system";
            if (!string.IsNullOrEmpty(call.ParameterListNoThis))
                parameters += $", {call.ParameterListNoThis}";

            var body = $"return {className}.{fieldName}.{call.MethodName}({call.ArgumentNamesNoThis});";

            sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation({call.InterceptVersion}, \"{call.InterceptData}\")]");
            sb.AppendLine($"        public static {call.ReturnType} {call.MethodName}_{counter}({parameters})");
            sb.AppendLine("        {");
            sb.AppendLine($"            {body}");
            sb.AppendLine("        }");
            sb.AppendLine();
            counter++;
        }
        sb.AppendLine("    }"); // end Interceptors

        sb.AppendLine("}"); // end namespace
        return sb.ToString();
    }

    private static string GetFieldName(string fullyQualifiedType)
    {
        var sanitized = fullyQualifiedType.Replace("global::", "");
        sanitized = sanitized.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(' ', '_').Replace(',', '_').Replace("::", "_");
        return $"___query_{sanitized}";
    }
}
