using Content.Shared.Crucible;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Exodus.Crucible.UI;

[GenerateTypedNameReferences]
public sealed partial class CrucibleWindow : FancyWindow
{
    public event Action? OnStartCookPressed;

    public CrucibleWindow()
    {
        RobustXamlLoader.Load(this);
        StartButton.OnPressed += _ => OnStartCookPressed?.Invoke();
    }

    public void UpdateState(CrucibleConsoleState state)
    {
        UpdateProgress(state);
        UpdateTimer(state);
        UpdateItem(state);
        UpdateStatus(state);
        UpdateControls(state);
    }

    private void UpdateProgress(CrucibleConsoleState state)
    {
        CookingProgress.Value = state.Progress;
    }

    private void UpdateTimer(CrucibleConsoleState state)
    {
        var visible = state.IsCooking && state.RemainingTime > 0;

        TimerLabel.Visible = visible;

        if (!visible)
            return;

        TimerLabel.Text = Loc.GetString(
            "crucible-window-timer",
            ("time", state.RemainingTime));
    }

    private void UpdateItem(CrucibleConsoleState state)
    {
       if (!state.HasItem)
       {
           ItemLabel.Text = Loc.GetString("crucible-window-item-none");
           return;
       }

       ItemLabel.Text = Loc.GetString(
           "crucible-window-item-label",
           ("item", state.ItemName));
    }

    private void UpdateStatus(CrucibleConsoleState state)
    {
        if (!state.HasItem)
        {
            SetStatus("crucible-window-status-waiting", Color.White);
            return;
        }

        if (state.IsCooking)
        {
            SetStatus("crucible-window-status-working", Color.Yellow);
            return;
        }

        if (state.CanCook)
        {
            SetStatus("crucible-window-status-ready", Color.LimeGreen);
            return;
        }

        SetStatus("crucible-window-status-error", Color.Red);
    }

    private void SetStatus(string locKey, Color color)
    {
        StatusLabel.Text = Loc.GetString(locKey);
        StatusLabel.FontColorOverride = color;
    }

    private void UpdateControls(CrucibleConsoleState state)
    {
        StartButton.Disabled = !state.CanCook || state.IsCooking;
    }
}
