- type: job
  id: PDVShagird
  name: job-name-pdv-shagird
  description: job-description-pdv-shagird
  playTimeTracker: JobPDVShagird
  startingGear: PDVShagirdGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPDVShagird"
  supervisors: job-supervisors-pirate
  weight: 10
  displayWeight: 10
  assignedCompany: PDV
  setPreference: true
  access:
  - Pirate
  - Mercenary
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - PirateNF
    - type: SpecialSectorStationRecord
      recordGeneration: NoRecord
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PDVShagirdGear
  equipment:
    ears: ClothingHeadsetAltFreelancer
    id: PDVShagirdPDA
  storage:
    back:
    - RadioHandheldNF
