// (c) Space Exodus Team - EXDS-RL with CLA

using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Content.Shared.SS220.EPA;

namespace Content.Client.SS220.UserInterface.EPA;

[GenerateTypedNameReferences]
public sealed partial class EPAAuthPanel : Control
{
    [Dependency] private IClientEPAManager _epa = default!;
    [Dependency] private IClientConsoleHost _consoleHost = default!;
    [Dependency] private IUriOpener _uri = default!;

    public EPAAuthPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        QuitButton.OnPressed += _ =>
        {
            _consoleHost.ExecuteCommand("quit");
        };

        UrlEdit.Text = _epa.AuthUrl ?? "";
        OpenUrlButton.OnPressed += (_) =>
        {
            if (!string.IsNullOrEmpty(_epa.AuthUrl))
            {
                _uri.OpenUri(_epa.AuthUrl);
            }
        };
    }
}
