using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Silicons.StationAi.UI;

[GenerateTypedNameReferences]
public sealed partial class AiRenameWindow : FancyWindow
{
    public event Action<string>? OnConfirmed;

    public AiRenameWindow()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ =>
        {
            var name = NameEdit.Text.Trim();
            if (string.IsNullOrWhiteSpace(name))
                return;
            OnConfirmed?.Invoke(name);
            Close();
        };

        CancelButton.OnPressed += _ => Close();

        NameEdit.OnTextEntered += _ =>
        {
            var name = NameEdit.Text.Trim();
            if (string.IsNullOrWhiteSpace(name))
                return;
            OnConfirmed?.Invoke(name);
            Close();
        };
    }

    public void SetCurrentName(string name)
    {
        NameEdit.Text = name;
    }
}
