- type: pointOfInterest
  parent: BaseMobilePOI
  id: BasePOI
  abstract: true
  addComponents:
  - type: ForceAnchor
  - type: Tag # Exodus
    tags: [ POI ]

# Mono

- type: pointOfInterest
  id: BaseMobilePOI
  abstract: true
  # # Exodus start - further raised base ring for even stronger territory spread
  minimumDistance: 7000
  maximumDistance: 14000
  # # Exodus end
  spawnGamePreset: [ NFAdventure, NFPirate, MonoStandard, MonoRogueTSF, MonoRogueUSSP, MonoTSFUSSP, MonoADS, MonoChimera, MonoMixed, MonoAllAtOnce ] # Behold my list of gamerules
  spawnGroup: Optional
  addComponents:
  - type: IFF
    color: "#ffa600"
    readOnly: true

- type: pointOfInterest
  parent: BaseMobilePOI
  id: BaseRepairablePOI
  abstract: true
  addComponents:
  - type: InitRepairSnapshot
