// (c) Space Exodus Team - EXDS-RL with CLA
// Authors: Lokilife
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Exodus.Gimmicks.Pheromones.UI;

[GenerateTypedNameReferences]
public sealed partial class PheromonesAskWindow : DefaultWindow
{
    public event Action<string>? OnPheromonesTextSent;

    public PheromonesAskWindow()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += e => OnPheromonesTextSent?.Invoke(PheromonesTextLineEdit.Text);
    }
}
