[game]
role_timers = false

[chat]
motd = "Тестовый запуск сервера Frontier на SS220, подробнее можно прочитать в официальном Discord проекта!\nЗаходите на наш Discord-сервер!\nhttps://discord.gg/ss220"
