using Content.Shared._Exodus.MedicalAlerts;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Shared.Maths;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client._Exodus.MedicalAlerts.UI;

[GenerateTypedNameReferences]
public sealed partial class MedAlertUiFragmentListEntry : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public MedAlertUiFragmentListEntry(MedicalAlertEntry entry)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AlertStatus.Text = Loc.GetString("med-alert-status", ("type", entry.AlertType));
        AlertPanel.ModulateSelfOverride = GetStatusColor(entry.AlertType);

        AlertSubject.Text = Loc.GetString("med-alert-ui-entry-subject",
            ("user", entry.SubjectName),
            ("specie", ResolveSpeciesName(entry.SpeciesId) ?? "null"));

        var grid = entry.GridName ?? Loc.GetString("med-alert-ui-unknown-grid");

        AlertLocation.Text = Loc.GetString("med-alert-ui-entry-location",
            ("grid", grid),
            ("position", $"({entry.Position.X}, {entry.Position.Y})"));

        AlertTime.Text = $"{(int) entry.CreatedAt.TotalHours:D2}:{entry.CreatedAt.Minutes:D2}:{entry.CreatedAt.Seconds:D2}";
    }

    private string? ResolveSpeciesName(ProtoId<SpeciesPrototype>? speciesId)
    {
        if (speciesId is not { } speciesProtoId || !_prototypeManager.TryIndex(speciesProtoId, out var species))
            return null;

        return Loc.GetString(species.Name);
    }

    private static Color GetStatusColor(MedicalAlertType type)
    {
        return type switch
        {
            MedicalAlertType.Death => Color.FromHex("#520c0c"),
            MedicalAlertType.Critical => Color.FromHex("#664a06"),
            MedicalAlertType.Revived => Color.FromHex("#01551e"),
            _ => Color.White,
        };
    }
}
