using Content.Shared._Exodus.MedicalAlerts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.MedicalAlerts.UI;

[GenerateTypedNameReferences]
public sealed partial class MedAlertUiFragmentList : Control
{
    public event Action? OnRefreshButtonPressed;
    public event Action? OnToggleNotificationPressed;

    public MedAlertUiFragmentList()
    {
        RobustXamlLoader.Load(this);
        RefreshButton.OnPressed += _ => OnRefreshButtonPressed?.Invoke();
        NotificationSwitch.OnPressed += _ => OnToggleNotificationPressed?.Invoke();
    }

    public void SetAlerts(IReadOnlyList<MedicalAlertEntry> entries)
    {
        AlertsContainer.RemoveAllChildren();

        if (entries.Count == 0)
        {
            NoAlertsLabel.Visible = true;
            return;
        }

        NoAlertsLabel.Visible = false;
        foreach (var entry in entries)
        {
            AlertsContainer.AddChild(new MedAlertUiFragmentListEntry(entry));
        }
    }

    public void SetNotificationsEnabled(bool notificationsEnabled)
    {
        NotificationSwitch.Text = Loc.GetString(notificationsEnabled
            ? "med-alert-ui-notification-on"
            : "med-alert-ui-notification-off");
    }
}
