using Content.Shared._Exodus.MedicalAlerts;
using Robust.Client.AutoGenerated;
using Robust.Shared.Maths;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.MedicalAlerts.UI;

[GenerateTypedNameReferences]
public sealed partial class MedAlertUiFragmentListEntry : Control
{
    public MedAlertUiFragmentListEntry(MedicalAlertEntry entry)
    {
        RobustXamlLoader.Load(this);

        AlertStatus.Text = Loc.GetString(GetStatusLocId(entry.AlertType));
        AlertPanel.ModulateSelfOverride = GetStatusColor(entry.AlertType);

        AlertSubject.Text = Loc.GetString("med-alert-ui-entry-subject",
            ("user", entry.SubjectName),
            ("specie", entry.SpeciesName));

        var grid = string.IsNullOrEmpty(entry.GridName) || entry.GridName == "null"
            ? Loc.GetString("med-alert-ui-unknown-grid")
            : entry.GridName;

        AlertLocation.Text = Loc.GetString("med-alert-ui-entry-location",
            ("grid", grid),
            ("position", $"({entry.PositionX}, {entry.PositionY})"));

        AlertTime.Text = entry.Timestamp.ToString(@"hh\:mm\:ss");
    }

    private static LocId GetStatusLocId(MedicalAlertType type)
    {
        return type switch
        {
            MedicalAlertType.Dead => "med-alert-status-dead",
            MedicalAlertType.Critical => "med-alert-status-critical",
            MedicalAlertType.Revived => "med-alert-status-revived",
            _ => "med-alert-status-critical",
        };
    }

    private static Color GetStatusColor(MedicalAlertType type)
    {
        return type switch
        {
            MedicalAlertType.Dead => Color.FromHex("#520c0c"),
            MedicalAlertType.Critical => Color.FromHex("#664a06"),
            MedicalAlertType.Revived => Color.FromHex("#01551e"),
            _ => Color.White,
        };
    }
}
