using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace SS220.Analyzers.Generators.EntityQueryInterceptorGenerator;

[Generator]
public class EntityQueryInterceptorGenerator : IIncrementalGenerator
{
    // ---- Вспомогательные методы (бывший Collector) ----

    private readonly struct InvocationCallInfo
    {
        public readonly string MethodName;
        public readonly string ComponentTypeName;
        public readonly int InterceptVersion;
        public readonly string InterceptData;
        public readonly string ReturnType;
        public readonly string ParameterListNoThis;
        public readonly string ArgumentNamesNoThis;

        public InvocationCallInfo(
            string methodName, string componentTypeName,
            int interceptVersion, string interceptData,
            string returnType, string parameterListNoThis, string argumentNamesNoThis)
        {
            MethodName = methodName;
            ComponentTypeName = componentTypeName;
            InterceptVersion = interceptVersion;
            InterceptData = interceptData;
            ReturnType = returnType;
            ParameterListNoThis = parameterListNoThis;
            ArgumentNamesNoThis = argumentNamesNoThis;
        }
    }

    private static bool IsMethodOnEntitySystem(IMethodSymbol method)
    {
        var type = method.ContainingType;
        while (type != null)
        {
            if (type.ToDisplayString() == "Robust.Shared.GameObjects.EntitySystem")
                return true;
            type = type.BaseType;
        }
        return false;
    }

    private static bool IsEntitySystemClass(INamedTypeSymbol symbol)
    {
        var baseType = symbol.BaseType;
        while (baseType != null)
        {
            if (baseType.ToDisplayString() == "Robust.Shared.GameObjects.EntitySystem")
                return true;
            baseType = baseType.BaseType;
        }
        return false;
    }

    private static bool IsPartial(INamedTypeSymbol classSymbol)
    {
        foreach (var decl in classSymbol.DeclaringSyntaxReferences)
        {
            if (decl.GetSyntax() is TypeDeclarationSyntax typeDecl
                && typeDecl.Modifiers.Any(SyntaxKind.PartialKeyword))
                return true;
        }
        return false;
    }

    private static INamedTypeSymbol? GetContainingClass(SyntaxNode node, SemanticModel model)
    {
        var parent = node.Parent;
        while (parent != null)
        {
            if (parent is TypeDeclarationSyntax typeDecl)
                return model.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
            parent = parent.Parent;
        }
        return null;
    }

    // ---- Генератор ----

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Атрибут InterceptsLocation (если отсутствует)
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("InterceptsLocationAttribute.g.cs", @"
// <auto-generated/>
#pragma warning disable CS0436
namespace System.Runtime.CompilerServices
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    internal sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data) { }
    }
}
");
        });

        var methodCalls = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is InvocationExpressionSyntax,
            transform: static (ctx, token) => TransformMethodCall(ctx, token)
        ).Where(static info => info is not null)!;

        var combined = methodCalls.Collect();
        context.RegisterSourceOutput(combined, GenerateSource);
    }

    private static (INamedTypeSymbol ContainingClass, InvocationCallInfo Call)? TransformMethodCall(
        GeneratorSyntaxContext ctx, CancellationToken token)
    {
        if (ctx.Node is not InvocationExpressionSyntax invocation)
            return null;

        var model = ctx.SemanticModel;
        if (model.GetSymbolInfo(invocation).Symbol is not IMethodSymbol method)
            return null;

        if (!IsMethodOnEntitySystem(method))
            return null;

        var containingClass = GetContainingClass(invocation, model);
        if (containingClass is null || !IsEntitySystemClass(containingClass))
            return null;

        if (!IsPartial(containingClass))
            return null;

        var methodName = method.Name;
        if (methodName is not ("TryComp" or "HasComp"))
            return null;

        if (method.TypeArguments.Length == 0)
            return null;

        var compType = method.TypeArguments[0];
        if (compType is ITypeParameterSymbol or not INamedTypeSymbol)
            return null;

        if (method.Parameters.Length == 0)
            return null;

        var interceptableLocation = model.GetInterceptableLocation(invocation, token);
        if (interceptableLocation == null)
            return null;
        var version = interceptableLocation.Version;
        var data = interceptableLocation.Data;

        var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var typeFormat = new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
        );

        var paramList = new List<string>();
        var argList = new List<string>();
        foreach (var p in method.Parameters)
        {
            string mod = p.RefKind switch { RefKind.Out => "out ", RefKind.Ref => "ref ", _ => "" };
            string type = p.Type.ToDisplayString(typeFormat);
            bool isNullableOut = p.RefKind == RefKind.Out && type.EndsWith("?");
            string paramDecl = isNullableOut
                ? $"[global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] {mod}{type} {p.Name}"
                : $"{mod}{type} {p.Name}";
            paramList.Add(paramDecl);
            argList.Add($"{mod}{p.Name}");
        }

        var callInfo = new InvocationCallInfo(
            methodName,
            ((INamedTypeSymbol)compType).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            version, data,
            returnType,
            string.Join(", ", paramList),
            string.Join(", ", argList)
        );

        return (containingClass, callInfo);
    }

    private static void GenerateSource(SourceProductionContext spc,
        ImmutableArray<(INamedTypeSymbol ContainingClass, InvocationCallInfo Call)?> methodCallsNullable)
    {
        var methodCalls = methodCallsNullable
            .Where(x => x.HasValue)
            .Select(x => x!.Value)
            .ToImmutableArray();

        var callsByClass = new Dictionary<INamedTypeSymbol, ImmutableArray<InvocationCallInfo>>(SymbolEqualityComparer.Default);
        foreach (var (containingClass, call) in methodCalls)
        {
            if (callsByClass.ContainsKey(containingClass))
                callsByClass[containingClass] = callsByClass[containingClass].Add(call);
            else
                callsByClass[containingClass] = ImmutableArray.Create(call);
        }

        foreach (var kvp in callsByClass)
        {
            var systemClass = kvp.Key;
            var calls = kvp.Value;
            var uniqueComponents = calls.Select(c => c.ComponentTypeName).Distinct().ToImmutableArray();

            spc.AddSource($"{systemClass.Name}.g.queries.cs", GenerateQueriesPartial(systemClass, uniqueComponents));
            spc.AddSource($"{systemClass.Name}.g.interceptors.cs", GenerateInterceptors(systemClass, calls));
        }
    }

    private static string GenerateQueriesPartial(INamedTypeSymbol systemClass, ImmutableArray<string> componentTypeNames)
    {
        var ns = systemClass.ContainingNamespace.IsGlobalNamespace ? null : systemClass.ContainingNamespace.ToDisplayString();
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0649");
        if (ns != null) { sb.AppendLine($"namespace {ns}"); sb.AppendLine("{"); }
        var indent = ns == null ? "" : "    ";
        sb.AppendLine($"{indent}public partial class {systemClass.Name}");
        sb.AppendLine($"{indent}{{");
        // Флаг ленивой инициализации
        sb.AppendLine($"{indent}    [global::System.Runtime.CompilerServices.CompilerGenerated]");
        sb.AppendLine($"{indent}    internal bool ___queriesInitialized = false;");
        sb.AppendLine();
        foreach (var compType in componentTypeNames)
        {
            var fieldName = GetFieldName(compType);
            sb.AppendLine($"{indent}    [global::System.Runtime.CompilerServices.CompilerGenerated]");
            sb.AppendLine($"{indent}    internal global::Robust.Shared.GameObjects.EntityQuery<{compType}> {fieldName};");
        }
        sb.AppendLine();
        sb.AppendLine($"{indent}    [global::System.Runtime.CompilerServices.CompilerGenerated]");
        sb.AppendLine($"{indent}    internal void ___InitializeQueries()");
        sb.AppendLine($"{indent}    {{");
        foreach (var compType in componentTypeNames)
        {
            var fieldName = GetFieldName(compType);
            sb.AppendLine($"{indent}        {fieldName} = this.GetEntityQuery<{compType}>();");
        }
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");
        if (ns != null) sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateInterceptors(INamedTypeSymbol systemClass, ImmutableArray<InvocationCallInfo> calls)
    {
        var fullName = systemClass.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using Robust.Shared.GameObjects;");
        sb.AppendLine();
        sb.AppendLine("namespace Content.Shared.GeneratedInterceptors");
        sb.AppendLine("{");
        sb.AppendLine($"    internal static class Interceptors_{systemClass.Name}");
        sb.AppendLine("    {");
        int counter = 0;
        foreach (var call in calls)
        {
            var fieldName = GetFieldName(call.ComponentTypeName);
            string parameters = "this EntitySystem __system";
            if (!string.IsNullOrEmpty(call.ParameterListNoThis))
                parameters += $", {call.ParameterListNoThis}";

            // Тело с ленивой инициализацией запросов
            string body = $@"
        var sys = ({fullName})__system;
        if (!sys.___queriesInitialized)
        {{
            sys.___InitializeQueries();
            sys.___queriesInitialized = true;
        }}
        return sys.{fieldName}.{call.MethodName}Comp({call.ArgumentNamesNoThis});".TrimStart();

            // Для TryComp имя метода в EntityQuery — TryGetComponent или TryComp?
            // В исходниках EntityQuery есть оба варианта: TryComp и HasComp.
            // Используем TryComp/HasComp напрямую, т.к. они есть в EntityQuery<T>.
            body = body.Replace("TryCompComp", "TryComp")  // на случай лишнего Comp
                       .Replace("HasCompComp", "HasComp");

            sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation({call.InterceptVersion}, \"{call.InterceptData}\")]");
            sb.AppendLine($"        public static {call.ReturnType} {call.MethodName}_{counter}({parameters})");
            sb.AppendLine("        {");
            sb.AppendLine($"            {body}");
            sb.AppendLine("        }");
            sb.AppendLine();
            counter++;
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetFieldName(string fullyQualifiedType)
    {
        var sanitized = fullyQualifiedType.Replace("global::", "");
        sanitized = sanitized.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(' ', '_').Replace(',', '_').Replace("::", "_");
        return $"___query_{sanitized}";
    }
}
