using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Cargo.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CargoProductRow : PanelContainer
    {
        /// <summary>Exodus: catalog product when from YAML cargo catalog; null for resale stock.</summary>
        public CargoProductPrototype? Product { get; set; }

        /// <summary>Exodus: plain description for the order dialog, independent of the card tooltip.</summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>Exodus: server listing id (cargo product id or resale:EntityId).</summary>
        public string ListingProductId { get; set; } = string.Empty;

        /// <summary>Exodus: true when this row is station resale stock from sold goods.</summary>
        public bool IsResale { get; set; }

        /// <summary>Exodus: max order amount for resale (null = unlimited catalog).</summary>
        public int? StockQuantity { get; set; }

        public CargoProductRow()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
