// Exodus dynamic market — sell console appraisal line
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class CargoPalletItemRow : PanelContainer
{
    public CargoPalletItemRow()
    {
        RobustXamlLoader.Load(this);
    }
}
