using System.Collections.Generic;
using Content.Client.UserInterface.Controls; // Exodus: use the shared terminal window chrome.
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client.Cargo.UI
{
    [GenerateTypedNameReferences]
    sealed partial class CargoConsoleOrderMenu : FancyWindow // Exodus: match the sector market terminal.
    {
        public CargoConsoleOrderMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Amount.SetButtons(new List<int> { -100, -10, -1 }, new List<int> { 1, 10, 100 }); // Exodus: quick bulk quantities.
            Amount.IsValid = n => n > 0;
        }
    }
}
