using System;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Exodus.Bank.UI;

[GenerateTypedNameReferences]
public sealed partial class SavingsWindow : FancyWindow
{
    /// <summary>
    /// Raised with the requested transfer amount. Positive moves main account -> savings,
    /// negative moves savings -> main account.
    /// </summary>
    public event Action<int>? OnTransfer;

    public SavingsWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("savings-window-title");

        ToSavingsButton.OnPressed += _ => Submit(1);
        ToAccountButton.OnPressed += _ => Submit(-1);
    }

    public void SetBalances(int account, long savings)
    {
        AccountLabel.Text = BankSystemExtensions.ToSpesoString(account);
        SavingsLabel.Text = BankSystemExtensions.ToSpesoString(savings);
    }

    private void Submit(int sign)
    {
        if (!int.TryParse(AmountEdit.Text, out var amount) || amount <= 0)
            return;

        OnTransfer?.Invoke(sign * amount);
    }
}
