// Exodus: gas sale UI with market lines + trends
using Content.Client._Exodus.Economy.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Exodus.Economy;
using Content.Shared._NF.Bank;
using Content.Shared.Atmos;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class GasSaleMenu : FancyWindow
{
    public Action? RefreshRequested;
    public Action? SellRequested;
    public string FallbackGasString = "gas-fallback";

    public GasSaleMenu()
    {
        RobustXamlLoader.Load(this);
        RefreshButton.OnPressed += OnRefreshPressed;
        SellButton.OnPressed += OnSellPressed;
    }

    public void SetMixture(GasMixture mixture, int appraisal, List<GasMarketLine>? lines = null)
    {
        GasLines.RemoveAllChildren();

        if (lines is { Count: > 0 })
        {
            foreach (var line in lines)
            {
                GasLines.AddChild(BuildLineRow(line));
            }
        }
        else
        {
            // Fallback without server lines (old state)
            var hasGas = false;
            for (var i = 0; i < Atmospherics.TotalNumberOfGases; i++)
            {
                var gasAmount = mixture.GetMoles(i);
                if (gasAmount <= 0)
                    continue;

                var gas = (Gas)i;
                var name = Atmospherics.GasNames.TryGetValue(gas, out var gasName)
                    ? gasName
                    : Loc.GetString(FallbackGasString, ("number", i));

                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                };
                row.AddChild(new Label { Text = name, HorizontalExpand = true, ClipText = true });
                row.AddChild(new Label
                {
                    Text = Loc.GetString("gas-sale-menu-quantity", ("value", gasAmount)),
                    MinWidth = 72,
                    Align = Label.AlignMode.Right,
                });
                GasLines.AddChild(row);
                hasGas = true;
            }

            if (!hasGas)
            {
                GasLines.AddChild(new Label { Text = Loc.GetString("gas-sale-menu-no-gases") });
            }
        }

        AppraisalLabel.Text = BankSystemExtensions.ToSpesoString(appraisal);
    }

    private Control BuildLineRow(GasMarketLine line)
    {
        var gas = (Gas)line.GasId;
        var name = Atmospherics.GasNames.TryGetValue(gas, out var gasName)
            ? gasName
            : Loc.GetString(FallbackGasString, ("number", line.GasId));

        var panel = new PanelContainer { HorizontalExpand = true };
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(4, 2),
        };

        row.AddChild(new Label
        {
            Text = name,
            HorizontalExpand = true,
            ClipText = true,
            VerticalAlignment = VAlignment.Center,
        });
        row.AddChild(new Label
        {
            Text = Loc.GetString("gas-sale-menu-quantity", ("value", line.Moles)),
            MinWidth = 72,
            Align = Label.AlignMode.Right,
            StyleClasses = { "LabelSubText" },
            VerticalAlignment = VAlignment.Center,
        });
        row.AddChild(new Label
        {
            Text = Loc.GetString("gas-sale-menu-unit-price", ("price", line.UnitPrice.ToString("N2"))),
            MinWidth = 72,
            Align = Label.AlignMode.Right,
            StyleClasses = { "LabelSubText" },
            VerticalAlignment = VAlignment.Center,
        });
        row.AddChild(new Label
        {
            Text = BankSystemExtensions.ToSpesoString(line.LineTotal),
            MinWidth = 72,
            Align = Label.AlignMode.Right,
            StyleClasses = { "LabelKeyText" },
            VerticalAlignment = VAlignment.Center,
        });

        var trend = new Label
        {
            MinWidth = 64,
            Align = Label.AlignMode.Right,
            StyleClasses = { "LabelSubText" },
            VerticalAlignment = VAlignment.Center,
        };
        MarketTerminalTheme.ApplyTrend(trend, line.Trend, line.ChangePercent); // Exodus: actual movement direction
        row.AddChild(trend);

        panel.PanelOverride = MarketTerminalTheme.MakeCardBox();
        panel.AddChild(row);
        return panel;
    }

    public void SetEnabled(bool enabled)
    {
        SellButton.Disabled = !enabled;
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs obj)
    {
        SellRequested?.Invoke();
    }

    private void OnRefreshPressed(BaseButton.ButtonEventArgs obj)
    {
        RefreshRequested?.Invoke();
    }
}
