using System.Linq;
using Content.Client._Exodus.Decals; // Exodus
using Content.Client.Stylesheets;
using Content.Shared.Decals;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.Decals.UI;

[GenerateTypedNameReferences]
public sealed partial class DecalPlacerWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IEntityManager _e = default!;

    private readonly DecalPlacementSystem _decalPlacementSystem;
    private readonly FavoriteDecalColorsSystem _favorites; // Exodus

    public FloatSpinBox RotationSpinBox;

    private PaletteColorPicker? _picker;

    private SortedDictionary<string, Texture>? _decals;
    private string? _selected;
    private Color _color = Color.White;
    private bool _useColor;
    private bool _snap;
    private float _rotation;
    private bool _cleanable;
    private int _zIndex;

    private bool _auto;

    public DecalPlacerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _decalPlacementSystem = _e.System<DecalPlacementSystem>();
        _favorites = _e.System<FavoriteDecalColorsSystem>(); // Exodus

        // This needs to be done in C# so we can have custom stuff passed in the constructor
        // and thus have a proper step size
        RotationSpinBox = new FloatSpinBox(90.0f, 0)
        {
            HorizontalExpand = true
        };
        SpinBoxContainer.AddChild(RotationSpinBox);

        Search.OnTextChanged += _ => RefreshList();
        ColorPicker.OnColorChanged += OnColorPicked;

        // Exodus-Start
        // Arm the eyedropper. Subscribe for this window instance's lifetime (unsubscribed in Dispose);
        // tying it to Opened/Close leaks a stale handler when the window is disposed without closing.
        EyedropperButton.OnPressed += _ => _decalPlacementSystem.SetEyedropper(!_decalPlacementSystem.EyedropperActive);
        _decalPlacementSystem.EyedropperPicked += OnEyedropperPicked;
        _decalPlacementSystem.DecalCopied += OnDecalCopied; // "O" copy hotkey

        // Star toggles the current color in/out of favorites; keep it lit when the color matches.
        FavoriteButton.OnPressed += _ =>
        {
            _favorites.Toggle(_color);
            UpdateFavoriteStar();
        };
        _favorites.FavoritesChanged += UpdateFavoriteStar;
        UpdateFavoriteStar();
        // Exodus-End

        PickerOpen.OnPressed += _ =>
        {
            if (_picker is null)
            {
                _picker = new PaletteColorPicker();
                _picker.OpenToLeft();
                _picker.PaletteList.OnItemSelected += args =>
                {
                    var color = (args.ItemList.GetSelected().First().Metadata as Color?)!.Value;
                    ColorPicker.Color = color;
                    OnColorPicked(color);
                };
            }
            else
            {
                if (_picker.IsOpen)
                {
                    _picker.Close();
                }
                else
                {
                    _picker.Open();
                }
            }
        };

        RotationSpinBox.OnValueChanged += args =>
        {
            _rotation = args.Value;
            UpdateDecalPlacementInfo();
        };
        EnableAuto.OnToggled += args =>
        {
            _auto = args.Pressed;
            if (_selected != null)
                SelectDecal(_selected);
        };
        EnableColor.OnToggled += args =>
        {
            _useColor = args.Pressed;
            UpdateDecalPlacementInfo();
            RefreshList();
        };
        EnableSnap.OnToggled += args =>
        {
            _snap = args.Pressed;
            UpdateDecalPlacementInfo();
        };
        EnableCleanable.OnToggled += args =>
        {
            _cleanable = args.Pressed;
            UpdateDecalPlacementInfo();
        };
        ZIndexSpinBox.ValueChanged += args =>
        {
            _zIndex = args.Value;
            UpdateDecalPlacementInfo();
        };
    }

    private void OnColorPicked(Color color)
    {
        _color = color;
        UpdateDecalPlacementInfo();
        RefreshList();
        UpdateFavoriteStar(); // Exodus
    }

    // Exodus-Start
    // Reflect whether the current color is saved as a favorite (★ lit / ☆ unlit).
    private void UpdateFavoriteStar()
    {
        // These run from a system event; a dead instance must not touch its controls (it would
        // throw and abort the event's multicast before live windows run).
        if (Disposed)
            return;

        var saved = _favorites.Contains(_color);
        FavoriteButton.Text = saved ? "★" : "☆";
        FavoriteButton.Modulate = saved ? Color.Gold : Color.White;
    }

    // Apply a color copied from a decal via the eyedropper tool.
    private void OnEyedropperPicked(Color color)
    {
        if (Disposed)
            return;

        // Make sure the copied color is actually used when placing.
        _useColor = true;
        EnableColor.Pressed = true;

        ColorPicker.Color = color;
        OnColorPicked(color);
    }

    // Mirror a decal copied from the map (hotkey "O") into the placer settings.
    private void OnDecalCopied(Decal decal)
    {
        if (Disposed)
            return;

        if (!_prototype.HasIndex<DecalPrototype>(decal.Id))
            return;

        _selected = decal.Id;

        _useColor = decal.Color != null;
        EnableColor.Pressed = _useColor;
        _color = decal.Color ?? Color.White;
        ColorPicker.Color = _color;

        _rotation = (float) decal.Angle.Degrees;
        RotationSpinBox.Value = _rotation;

        _zIndex = decal.ZIndex;
        ZIndexSpinBox.Value = _zIndex;

        _cleanable = decal.Cleanable;
        EnableCleanable.Pressed = _cleanable;

        UpdateDecalPlacementInfo();
        RefreshList();
        UpdateFavoriteStar();
    }
    // Exodus-End

    private void UpdateDecalPlacementInfo()
    {
        if (_selected is null)
            return;

        var color = _useColor ? _color : Color.White;
        _decalPlacementSystem.UpdateDecalInfo(_selected, color, _rotation, _snap, _zIndex, _cleanable);
    }

    private void RefreshList()
    {
        // Clear
        Grid.RemoveAllChildren();
        if (_decals == null)
            return;

        var filter = Search.Text;
        foreach (var (decal, tex) in _decals)
        {
            if (!decal.ToLowerInvariant().Contains(filter.ToLowerInvariant()))
                continue;

            var button = new TextureButton
            {
                TextureNormal = tex,
                Name = decal,
                ToolTip = decal,
                Modulate = _useColor ? _color : Color.White
            };
            button.OnPressed += ButtonOnPressed;
            if (_selected == decal)
            {
                var panelContainer = new PanelContainer
                {
                    PanelOverride = new StyleBoxFlat
                    {
                        BackgroundColor = StyleNano.ButtonColorDefault
                    },
                    Children =
                    {
                        button
                    }
                };
                Grid.AddChild(panelContainer);
            }
            else
                Grid.AddChild(button);
        }
    }

    private void ButtonOnPressed(ButtonEventArgs obj)
    {
        if (obj.Button.Name == null)
            return;

        // Exodus-Start: clicking the already-selected decal again clears the selection
        // instead of leaving it stuck to the cursor.
        if (obj.Button.Name == _selected)
        {
            _selected = null;
            _decalPlacementSystem.ClearDecal();
            RefreshList();
            return;
        }
        // Exodus-End

        SelectDecal(obj.Button.Name);
    }

    private void SelectDecal(string decalId)
    {
        if (!_prototype.TryIndex<DecalPrototype>(decalId, out var decal))
            return;

        _selected = decalId;

        if (_auto)
        {
            EnableCleanable.Pressed = decal.DefaultCleanable;
            EnableColor.Pressed = decal.DefaultCustomColor;
            EnableSnap.Pressed = decal.DefaultSnap;
            _cleanable = decal.DefaultCleanable;
            _useColor = decal.DefaultCustomColor;
            _snap = decal.DefaultSnap;
        }
        UpdateDecalPlacementInfo();
        RefreshList();
    }

    public void Populate(IEnumerable<DecalPrototype> prototypes)
    {
        _decals = new SortedDictionary<string, Texture>();
        foreach (var decalPrototype in prototypes)
        {
            if (decalPrototype.ShowMenu)
                _decals.Add(decalPrototype.ID, decalPrototype.Sprite.Frame0());
        }

        RefreshList();
    }

    protected override void Opened()
    {
        base.Opened();
        _decalPlacementSystem.SetActive(true);
    }

    public override void Close()
    {
        base.Close();
        _decalPlacementSystem.SetActive(false);
    }

    // Exodus-Start: drop subscriptions and owned windows when this instance is destroyed.
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
        {
            _decalPlacementSystem.EyedropperPicked -= OnEyedropperPicked;
            _decalPlacementSystem.DecalCopied -= OnDecalCopied;
            _favorites.FavoritesChanged -= UpdateFavoriteStar;
            // The palette picker is owned by this window; dispose it so its own
            // FavoritesChanged subscription doesn't leak past this window's lifetime.
            _picker?.Dispose();
        }
    }
    // Exodus-End
}
