using Content.Client._Exodus.Decals; // Exodus
using Content.Shared.Decals;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Decals.UI;

[GenerateTypedNameReferences]
public sealed partial class PaletteColorPicker : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IResourceCache _resourceCache = default!;
    [Dependency] private IEntityManager _entManager = default!; // Exodus

    private readonly TextureResource _tex;

    // Exodus: sentinel metadata marking the synthetic "Favorites" entry (not a prototype).
    private static readonly object FavoritesMarker = new();
    private readonly FavoriteDecalColorsSystem _favorites; // Exodus

    public PaletteColorPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _favorites = _entManager.System<FavoriteDecalColorsSystem>(); // Exodus

        _tex = _resourceCache.GetResource<TextureResource>("/Textures/Interface/Nano/button.svg.96dpi.png");

        var i = 0;
        foreach (var palette in _prototypeManager.EnumeratePrototypes<ColorPalettePrototype>())
        {
            if (palette.Hidden) // Frontier: selectively hide palettes
                continue; // Frontier: selectively hide palettes
            Palettes.AddItem(palette.Name);
            Palettes.SetItemMetadata(i, palette); // ew
            i += 1;
        }

        // Exodus: append the user's favorites as a synthetic palette.
        Palettes.AddItem(Loc.GetString("decal-placer-palette-favorites"));
        Palettes.SetItemMetadata(i, FavoritesMarker);
        _favorites.FavoritesChanged += OnFavoritesChanged;

        Palettes.OnItemSelected += args =>
        {
            Palettes.SelectId(args.Id);
            SetupList();
        };

        Palettes.Select(0);
        SetupList();
    }

    private void SetupList()
    {
        PaletteList.Clear();

        // Exodus: the Favorites entry is dynamic, the rest are static prototypes.
        if (Palettes.SelectedMetadata is ColorPalettePrototype palette)
        {
            foreach (var (name, value) in palette.Colors)
            {
                var item = PaletteList.AddItem(name, _tex.Texture);
                item.Metadata = value;
                item.IconModulate = value;
            }
        }
        else
        {
            foreach (var color in _favorites.Colors)
            {
                var item = PaletteList.AddItem(color.ToHex(), _tex.Texture);
                item.Metadata = color;
                item.IconModulate = color;
            }
        }
    }

    // Exodus: refresh while the favorites palette is shown (e.g. the star added/removed a color).
    private void OnFavoritesChanged()
    {
        // Runs from a system event; a dead instance must not touch its controls.
        if (Disposed)
            return;

        if (Palettes.SelectedMetadata is not ColorPalettePrototype)
            SetupList();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing) // Exodus
            _favorites.FavoritesChanged -= OnFavoritesChanged;
    }
}
